# Use PHP 8.2 with Apache
FROM php:8.4-apache

# Install System Dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    acl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpq-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql pdo_pgsql mbstring exif pcntl bcmath gd zip

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Raise max_input_vars: PO items can carry 200+ rolls, and the roll-editing
# form posts ~9 fields per roll, well past PHP's default 1000-var cutoff —
# see docker/php/php-overrides.ini for the failure mode this causes.
COPY docker/php/php-overrides.ini /usr/local/etc/php/conf.d/zz-app-overrides.ini

# Set Document Root to public folder
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf
RUN sed -ri -e 's!AllowOverride None!AllowOverride All!g' /etc/apache2/apache2.conf

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy application files
COPY . .

# Install PHP dependencies (Optimize for production)
RUN composer install --no-dev --optimize-autoloader --no-interaction

# Create SQLite database file if it doesn't exist (for initial run)
RUN if [ ! -f database/database.sqlite ]; then touch database/database.sqlite; fi

# Link public/storage -> storage/app/public. public/storage is gitignored and
# dockerignored (never baked into the image), so without this the QR code /
# packing-slip PDF links generated by the app 404 on any fresh container.
RUN php artisan storage:link

# Set Permissions.
# `docker exec` (no -u flag) runs as root by default, so `artisan`/`tinker` run
# ad hoc against this container write root-owned cache files into storage/. The
# Apache worker processes run as www-data and can't overwrite those on the next
# request (file mode denies "other" write despite the 777 directory), producing
# a 500 on any page that (re)compiles a view or writes a cache file. The default
# ACL below grants www-data rwx on every file created here from now on,
# regardless of which user creates it, closing that gap permanently.
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache /var/www/html/database \
    && setfacl -R -m u:www-data:rwx /var/www/html/storage /var/www/html/bootstrap/cache \
    && setfacl -R -d -m u:www-data:rwx /var/www/html/storage /var/www/html/bootstrap/cache

# Expose Port 80 (Internal) -> server will map to 8080
EXPOSE 80

# Start Apache
CMD ["apache2-foreground"]
