{{-- Server-side render of the QC Console's inspection report (PrintReport.tsx
     port). Generated by QcReportPdfService for email attachments, verified_doc
     regeneration, and RPA payloads — structural match, DomPDF-compatible
     (tables only, no flexbox). --}}
@php
    $n = fn ($v) => number_format((float) ($v ?? 0), 0, ',', '.');
    $rp = fn ($v) => 'Rp '.number_format(round((float) ($v ?? 0)), 0, ',', '.');
    $pct = fn ($num, $den) => $den > 0 ? number_format($num / $den * 100, 2).'%' : '0.00%';
    $fmtCons = fn ($v) => ($v !== null && $v !== '') ? number_format((float) $v, 4, ',', '.') : '—';
    $fmtPercent = fn ($v) => ($v !== null && $v !== '') ? number_format((float) ($v * 100), 2, ',', '.').'%' : '—';
    $fmtDate = function ($v) {
        if (empty($v)) return '—';
        try { return \Carbon\Carbon::parse($v)->format('d/m/Y'); } catch (\Throwable $e) { return (string) $v; }
    };
    $shortLabel = fn ($s) => (! $s || strlen($s) <= 42) ? $s : rtrim(substr($s, 0, 28)).' ... '.ltrim(substr($s, -13));
    // Signature-box email: no wrapping room — truncate like 'fitri.yeni@megape...'.
    $shortEmail = fn ($e) => (! $e || strlen($e) <= 24) ? $e : substr($e, 0, 21).'...';

    // Defect summary grouped by (type, description) — active-cycle images only.
    $defectGroups = [];
    $totMajor = 0; $totMinor = 0;
    foreach ($defectImages as $img) {
        $type = $img->defect_type ?: 'General';
        $desc = trim((string) ($img->description ?? '')) ?: 'No description';
        $key = $type.'_'.$desc;
        $defectGroups[$key] ??= ['type' => $type, 'desc' => $desc, 'major' => 0, 'minor' => 0];
        $defectGroups[$key]['major'] += (int) ($img->major ?? 0);
        $defectGroups[$key]['minor'] += (int) ($img->minor ?? 0);
        $totMajor += (int) ($img->major ?? 0);
        $totMinor += (int) ($img->minor ?? 0);
    }

    $fabricDeductionLines = $fabricLines->filter(fn ($f) => ($f->deduction ?? 0) > 0)->values();
    $manualTotal = $deductionLines->sum('amount');
    $fabricDeductionTotal = $fabricDeductionLines->sum('deduction');
    $penaltyTotal = $deductions['rejectProduksiPenalty'] + $deductions['barangHilangPenalty'];
    $grandTotal = $penaltyTotal + $manualTotal + $fabricDeductionTotal;
    $hasAnyDeduction = $deductions['exceedingRejectQty'] > 0 || $deductions['sumBarangHilang'] > 0
        || $deductionLines->isNotEmpty() || $fabricDeductionLines->isNotEmpty();

    $embeddableImages = $defectImages->filter(fn ($i) => str_starts_with((string) ($i->image_path ?? ''), 'data:image'))->values();
    $result = strtoupper((string) ($session->result ?? 'PENDING')) ?: 'PENDING';
    $resultColor = $result === 'PASSED' ? '#059669' : ($result === 'FAILED' ? '#DC2626' : '#D97706');
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 34pt 28pt 28pt 28pt; }
        body { font-family: Helvetica, Arial, sans-serif; color: #0F172A; font-size: 7.2pt; margin: 0; }
        table { border-collapse: collapse; width: 100%; }
        .tbl th, .tbl td { border: 0.6px solid #CBD5E1; padding: 2px 3px; font-size: 6.2pt; }
        .tbl th { background-color: #F8FAFC; color: #0F172A; font-weight: 500; text-transform: uppercase; font-size: 5.8pt; letter-spacing: 0.02em; }
        .section-title { font-size: 7.5pt; font-weight: bold; color: #0F172A; border-bottom: 1.5px solid rgba(15, 23, 42, 0.12); margin: 8px 0 4px; padding-bottom: 2px; text-transform: uppercase; letter-spacing: 0.03em; }
        .muted { color: #64748B; }
        .center { text-align: center; }
        .right { text-align: right; }
        .bold { font-weight: bold; }
        .sig-badge { display: inline-block; border: 1px solid #10B981; border-radius: 3px; color: #10B981; font-size: 5.4pt; font-weight: bold; padding: 1px 4px; text-transform: uppercase; }
        .sig-badge.rejected { border-color: #EF4444; color: #EF4444; }
        .sig-badge.pending { border: none; color: #94A3B8; font-style: italic; text-transform: none; font-weight: normal; font-size: 6pt; }
    </style>
</head>
<body>

{{-- Header --}}
<table style="border-bottom: 1.5px solid #0F172A; margin-bottom: 5px;">
    <tr>
        <td style="width: 45%; vertical-align: bottom;">
            @if ($logoData)
                <img src="{{ $logoData }}" style="height: 76px;">
            @endif
        </td>
        <td style="width: 55%; text-align: right; vertical-align: bottom; padding-bottom: 3px;">
            <div style="font-size: 11pt; font-weight: bold;">{{ $cycleName }} Inspection</div>
            <div style="font-size: 6pt;" class="muted">and</div>
            <div style="font-size: 11pt; font-weight: bold;">Official Report (Berita Acara)</div>
            <div style="font-size: 6.2pt; font-weight: bold;" class="muted">QUALITY CONTROL SYSTEM</div>
        </td>
    </tr>
</table>

{{-- Section 1: Overview --}}
<div class="section-title">1. Inspection Overview</div>
<table class="tbl">
    <tr>
        <th style="width: 12%;">Vendor</th><td colspan="5">{{ $project->po_vendor ?: '—' }}</td>
        <th style="width: 12%;">PO Number</th><td>{{ $project->po_info ?: '—' }}</td>
    </tr>
    <tr>
        <th>Article Name</th><td colspan="5">{{ $project->article_name ?: '—' }}</td>
        <th>Qty Order</th><td>{{ $project->po_qty ? $n($project->po_qty) : '—' }}</td>
    </tr>
    <tr>
        <th>Inspection Date</th><td>{{ $fmtDate($session->inspection_date) }}</td>
        <th>Available Qty</th><td>{{ $session->qty_available ? $n($session->qty_available) : '—' }}</td>
        <th>Total Store</th><td>{{ $session->total_store ?: '—' }}</td>
        <th>Store Inspected</th><td>{{ $session->store_inspected ?: '—' }}</td>
    </tr>
    <tr>
        <th>Delivery Plan</th><td>{{ $fmtDate($project->po_plan_date) }}</td>
        <th>Season</th><td>{{ $project->season ?: '—' }}</td>
        <th>PLM ID</th><td>{{ $project->plm_id ?: '—' }}</td>
        <th>Production Group</th><td>{{ $project->production_group ?: '—' }}</td>
    </tr>
</table>

{{-- Section 2: QC Status --}}
<div class="section-title">2. Quality Control Status</div>
<table style="margin-bottom: 6px; width: 100%; border-collapse: collapse; border: none;">
    <tr>
        @if (count($checklist))
            <td style="width: 40%; vertical-align: top; padding-right: 8px; border: none;">
                <table style="width: 100%; border: 0.6px solid #E2E8F0; border-radius: 6px; background: #F8FAFC; border-collapse: separate; border-spacing: 0;">
                    <tr>
                        <td colspan="2" style="font-size: 6.2pt; font-weight: 700; color: #0F172A; text-transform: uppercase; border-bottom: 0.6px solid #E2E8F0; padding: 3.5px 7px; letter-spacing: 0.02em; border-top-left-radius: 6px; border-top-right-radius: 6px;">
                            Garment Checklist
                        </td>
                    </tr>
                    @foreach (array_chunk($checklist, 2) as $pair)
                        <tr>
                            @foreach ($pair as $label)
                                <td style="font-size: 6pt; padding: 2px 7px; color: #0F172A; font-weight: 500; border: none; vertical-align: middle;">
                                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAXklEQVR4nGP8//8/AymAiSTVxGpQS3kDdwZBDTDFMJpoJ92aI8JIUAOyU7A6CVkBMhtmOgMDAwMjLFixmYauGMUGdAlcYkyEFGCA////Y2DV5Nf/sYn///8f4QdiAQDsNEbR9M9VLgAAAABJRU5ErkJggg==" style="width: 8px; height: 8px; margin-right: 3px; display: inline-block; vertical-align: middle; margin-top: -1.5px;">{{ $label }}
                                </td>
                            @endforeach
                            @if (count($pair) === 1)
                                <td style="border: none;"></td>
                            @endif
                        </tr>
                    @endforeach
                </table>
            </td>
        @endif
        <td style="vertical-align: top; border: none;">
            <table style="width: 100%; border: 0.6px solid #E2E8F0; border-radius: 6px; background: #F8FAFC; border-collapse: separate; border-spacing: 0; padding: 3.5px 7px; font-size: 6.2pt; font-weight: 600; color: #0F172A; margin-bottom: 4px;">
                <tr>
                    <td style="border: none; padding: 0;">SAMPLING: <strong>{{ $session->sampling_pcs ?: 0 }}</strong></td>
                    <td style="border: none; padding: 0; text-align: center;">AQL: <strong>{{ $session->aql ?: '—' }}</strong></td>
                    <td style="border: none; padding: 0; text-align: right;">LEVEL: <strong>{{ $session->level_val ?: '—' }}</strong></td>
                </tr>
            </table>
            <table class="tbl">
                <tr><th style="width: 80%;">Defect Type &amp; Description</th><th class="center">Major</th><th class="center">Minor</th></tr>
                @forelse ($defectGroups as $d)
                    <tr>
                        <td>[{{ (int) $session->cycle_number >= 2 ? $cycleName.'|'.$d['type'] : $d['type'] }}] {{ $d['desc'] }}</td>
                        <td class="center {{ $d['major'] > 0 ? 'bold' : '' }}">{{ $d['major'] }}</td>
                        <td class="center {{ $d['minor'] > 0 ? 'bold' : '' }}">{{ $d['minor'] }}</td>
                    </tr>
                @empty
                    <tr><td colspan="3" class="center muted" style="padding: 6px;">No defects logged in this session.</td></tr>
                @endforelse
                <tr style="background: #F8FAFC;" class="bold">
                    <td>TOTAL</td>
                    <td class="center" style="color: {{ $totMajor > 0 ? '#DC2626' : '#0F172A' }};">{{ $totMajor }}</td>
                    <td class="center" style="color: {{ $totMinor > 0 ? '#D97706' : '#0F172A' }};">{{ $totMinor }}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

{{-- Section 3: Yield Matrix --}}
<div class="section-title">3. Sizing &amp; Production Yield Matrix</div>
<table style="border: 0.6px solid #E2E8F0; background: #F8FAFC; margin-bottom: 3px;">
    <tr>
        <td style="font-size: 6.4pt; font-weight: bold; padding: 3px 6px;">CUTTING: {{ $n($session->cutting_pcs) }} PCS</td>
        <td style="font-size: 6.4pt; font-weight: bold; padding: 3px 6px;" class="center">SEWING: {{ $n($session->sewing_pcs) }} PCS</td>
        <td style="font-size: 6.4pt; font-weight: bold; padding: 3px 6px;" class="center">FINISHING: {{ $n($session->finishing_pcs) }} PCS</td>
        <td style="font-size: 6.4pt; font-weight: bold; padding: 3px 6px;" class="right">PACKING: {{ $n($session->packing_pcs) }} PCS</td>
    </tr>
</table>
<table class="tbl">
    <tr>
        <th rowspan="3">Size</th>
        <th rowspan="3">Order<br>Qty</th>
        <th rowspan="3">Cutting<br>Qty</th>
        <th rowspan="3">Good<br>Qty</th>
        <th colspan="10">Reject Category</th>
        <th rowspan="3">Total<br>Reject</th>
        <th rowspan="3">WIP</th>
        <th colspan="3">Partial Delivery</th>
        <th rowspan="3">Total<br>Delivery FG</th>
        <th rowspan="3">Goods Receive<br>Delivery</th>
    </tr>
    <tr>
        <th colspan="7">Produksi</th>
        <th rowspan="2">Bahan</th>
        <th rowspan="2">BTJ</th>
        <th rowspan="2">Barang<br>Hilang</th>
        <th rowspan="2">I</th><th rowspan="2">II</th><th rowspan="2">III</th>
    </tr>
    <tr>
        <th>Cut</th><th>Sew</th><th>Print</th><th>Embro</th><th>Wash</th><th>Finish</th><th style="background:#E2E8F0;">Total</th>
    </tr>
    @foreach ($rows as $r)
        <tr class="center">
            <td class="bold">{{ $r['size'] }}</td>
            <td>{{ $n($r['orderQty']) }}</td>
            <td>{{ $n($r['cuttingQty']) }}</td>
            <td>{{ $n($r['goodGarments']) }}</td>
            <td>{{ $r['rejectCutting'] }}</td>
            <td>{{ $r['rejectSewing'] }}</td>
            <td>{{ $r['rejectPrinting'] }}</td>
            <td>{{ $r['rejectEmbro'] }}</td>
            <td>{{ $r['rejectWashing'] }}</td>
            <td>{{ $r['rejectFinishing'] }}</td>
            <td class="bold" style="background: #F8FAFC;">{{ $n($r['rejectProduksi']) }}</td>
            <td>{{ $r['rejectBahan'] }}</td>
            <td>{{ $r['rejectBtj'] }}</td>
            <td>{{ $r['barangHilang'] }}</td>
            <td class="bold" style="color: {{ $r['totalReject'] > 0 ? '#DC2626' : '#0F172A' }};">{{ $n($r['totalReject']) }}</td>
            <td>{{ $n($r['wip']) }}</td>
            <td>{{ $r['qtyI'] > 0 ? $n($r['qtyI']) : '—' }}</td>
            <td>{{ $r['qtyII'] > 0 ? $n($r['qtyII']) : '—' }}</td>
            <td>{{ $r['qtyIII'] > 0 ? $n($r['qtyIII']) : '—' }}</td>
            <td class="bold" style="color: #059669;">{{ $n($r['totalDeliveryFG']) }}</td>
            <td class="bold" style="color: #2563EB;">{{ $n($r['goodsReceiveDelivery']) }}</td>
        </tr>
    @endforeach
    <tr class="center bold" style="background: #F8FAFC;">
        <td>TOTAL</td>
        <td>{{ $n($totals['orderQty']) }}</td>
        <td>{{ $n($totals['cuttingQty']) }}</td>
        <td>{{ $n($totals['goodGarments']) }}<br><span class="muted" style="font-size: 5pt;">({{ $pct($totals['goodGarments'], $totals['cuttingQty']) }})</span></td>
        <td>{{ $totals['rejectCutting'] }}</td>
        <td>{{ $totals['rejectSewing'] }}</td>
        <td>{{ $totals['rejectPrinting'] }}</td>
        <td>{{ $totals['rejectEmbro'] }}</td>
        <td>{{ $totals['rejectWashing'] }}</td>
        <td>{{ $totals['rejectFinishing'] }}</td>
        <td style="background: #E2E8F0;">{{ $n($totals['rejectProduksi']) }}<br><span class="muted" style="font-size: 5pt;">({{ $pct($totals['rejectProduksi'], $totals['cuttingQty']) }})</span></td>
        <td>{{ $totals['rejectBahan'] }}</td>
        <td>{{ $totals['rejectBtj'] }}</td>
        <td>{{ $totals['barangHilang'] }}</td>
        <td style="color: {{ $totals['totalReject'] > 0 ? '#DC2626' : '#0F172A' }};">{{ $n($totals['totalReject']) }}<br><span class="muted" style="font-size: 5pt;">({{ $pct($totals['totalReject'], $totals['cuttingQty']) }})</span></td>
        <td>{{ $n($totals['wip']) }}</td>
        <td>{{ $totals['qtyI'] > 0 ? $n($totals['qtyI']) : '—' }}</td>
        <td>{{ $totals['qtyII'] > 0 ? $n($totals['qtyII']) : '—' }}</td>
        <td>{{ $totals['qtyIII'] > 0 ? $n($totals['qtyIII']) : '—' }}</td>
        <td style="color: #059669;">{{ $n($totals['totalDeliveryFG']) }}<br><span style="font-size: 5pt; color: #059669;">({{ $pct($totals['totalDeliveryFG'], $totals['cuttingQty']) }})</span></td>
        <td style="color: #2563EB;">{{ $n($totals['goodsReceiveDelivery']) }}</td>
    </tr>
</table>

{{-- Fabric summary lines --}}
@if ($fabricLines->isNotEmpty())
    <table style="margin-top: 4px;">
        @foreach ($fabricLines as $f)
            <tr>
                <td style="font-size: 5.8pt; color: #334155; border-top: {{ $loop->first ? '0.6px solid #E2E8F0' : 'none' }}; padding: 3px 1px; line-height: 1.5;">
                    <div>
                        @if ($f->label)<span style="font-weight: 700; color: #0F172A; margin-right: 4px;">{{ $f->label }}</span>@endif
                        <span class="muted bold">Fabric Sent:</span> <span style="color: #0F172A;">{{ $f->fabric_sent !== null ? $n($f->fabric_sent) : '0' }}</span> &nbsp;
                        <span class="muted bold">Short Roll:</span> <span style="color: #0F172A;">{{ $f->short_roll !== null ? $n($f->short_roll) : '0' }}</span> &nbsp;
                        <span class="muted bold">Sisa Kain (utuh):</span> <span style="color: #0F172A;">{{ $f->sisa_kain !== null ? $n($f->sisa_kain) : '0' }}</span> &nbsp;
                        <span class="muted bold">Kepala Kain:</span> <span style="color: #0F172A;">{{ $f->kepala_kain !== null ? $n($f->kepala_kain) : '0' }}</span> &nbsp;
                        <span class="muted bold">Retur Kain:</span> <span style="color: #0F172A;">{{ $f->return_kain !== null ? $n($f->return_kain) : '0' }}</span>
                    </div>
                    @php
                        preg_match('/\(([A-Za-z0-9]+)\)\s*$/', (string) $f->label, $uMatch);
                        $unit = isset($uMatch[1]) ? ' '.$uMatch[1] : '';
                    @endphp
                    <div style="margin-top: 1px; padding-left: 8px;">
                        <span style="display: inline-block; width: 3px; height: 5px; border-left: 0.6px solid #94A3B8; border-bottom: 0.6px solid #94A3B8; margin-right: 3.5px; margin-left: 2px; vertical-align: middle; margin-top: -3.5px;"></span>
                        <span class="muted bold">Cutt Plan:</span> <span style="color: #0F172A;">{{ $f->cutt_plan !== null ? $n($f->cutt_plan).' Pcs' : '—' }}</span> &nbsp;
                        <span class="muted bold">Plan Cons:</span> <span style="color: #0F172A;">{{ $f->consumption_plan !== null ? $fmtCons($f->consumption_plan).$unit : '—' }}</span> &nbsp;
                        <span class="muted bold">Actual Cons:</span> <span style="color: #0F172A;">{{ $f->actual_consumption !== null ? $fmtCons($f->actual_consumption).$unit : '—' }}</span> &nbsp;
                        <span class="muted bold">Budget Cap (3%):</span> <span style="color: #0F172A;">{{ $f->consumption_plan !== null ? $fmtCons($f->consumption_plan * 1.03).$unit : '—' }}</span> &nbsp;
                        <span class="muted bold">Overconsumption:</span> <span style="color: {{ $f->overconsumption !== null && $f->overconsumption > 0.03 ? '#DC2626' : '#0F172A' }}; font-weight: {{ $f->overconsumption !== null && $f->overconsumption > 0.03 ? '700' : '500' }};">{{ $f->overconsumption !== null ? (number_format($f->overconsumption * 100, 2) . '%') : '—' }}</span>
                    </div>
                </td>
            </tr>
        @endforeach
    </table>
@endif

{{-- Section 4: Deductions & Remarks --}}
<div class="section-title">4. Deductions &amp; Remarks</div>
<table class="tbl">
    <tr>
        <th style="width: 30%;">Description</th>
        <th style="width: 15%;" class="center">Price/Pcs</th>
        <th style="width: 25%;">Reason</th>
        <th style="width: 15%;" class="center">Qty</th>
        <th style="width: 15%;" class="center">Amount</th>
    </tr>
    @if (! $hasAnyDeduction)
        <tr><td colspan="5" class="center muted" style="padding: 6px;">No deductions &amp; remarks logged for this session.</td></tr>
    @else
        @if ($deductions['exceedingRejectQty'] > 0)
            <tr>
                <td>Production Reject Penalty (Exceeding 1% Limit)</td>
                <td class="center">{{ $rp($deductions['penaltyPrice']) }}</td>
                <td>Total reject {{ $deductions['sumRejectProduksi'] }} exceeds 1% of cutting qty ({{ $deductions['sumCuttingQty'] }}) by {{ $deductions['exceedingRejectQty'] }} pcs</td>
                <td class="center">{{ $deductions['exceedingRejectQty'] }}</td>
                <td class="center">{{ $rp($deductions['rejectProduksiPenalty']) }}</td>
            </tr>
        @endif
        @if ($deductions['sumBarangHilang'] > 0)
            <tr>
                <td>Lost Items Penalty (Barang Hilang)</td>
                <td class="center">{{ $rp($deductions['penaltyPrice']) }}</td>
                <td>Lost {{ $deductions['sumBarangHilang'] }} pcs during production</td>
                <td class="center">{{ $deductions['sumBarangHilang'] }}</td>
                <td class="center">{{ $rp($deductions['barangHilangPenalty']) }}</td>
            </tr>
        @endif
        @foreach ($fabricDeductionLines as $f)
            @php
                preg_match('/\(([A-Z]+)\)\s*$/', (string) $f->label, $unitMatch);
                $unit = strtolower($unitMatch[1] ?? 'unit');
                $lbl = (string) $f->label;
                $formattedLabel = strlen($lbl) <= 42 ? $lbl : trim(substr($lbl, 0, 28)).' ... '.trim(substr($lbl, -13));
            @endphp
            <tr>
                <td>Fabric Overconsumption{{ $f->label ? ' — '.$formattedLabel : '' }}</td>
                <td class="center">{{ $f->fabric_price !== null ? $rp($f->fabric_price).' /'.$unit : '—' }}</td>
                <td>{{ $f->overconsumption !== null ? number_format($f->overconsumption * 100, 2).'% overconsumption' : '—' }}</td>
                <td class="center">—</td>
                <td class="center">{{ $rp($f->deduction) }}</td>
            </tr>
        @endforeach
        @foreach ($deductionLines as $line)
            <tr>
                <td>{{ $line->description }}</td>
                <td class="center">—</td>
                <td>{{ $line->created_by ? 'Added by '.$line->created_by : '—' }}</td>
                <td class="center">—</td>
                <td class="center">{{ $rp($line->amount) }}</td>
            </tr>
        @endforeach
        <tr class="bold" style="background: #F8FAFC;">
            <td colspan="4" class="right" style="padding-right: 10px;">Total Deductions</td>
            <td class="center">{{ $rp($grandTotal) }}</td>
        </tr>
    @endif
</table>
<div style="font-size: 6.2pt; margin: 4px 0 6px;">
    <span class="bold">Remarks:</span>
    <span style="{{ $remarks ? '' : 'color: #94A3B8; font-style: italic;' }}">{{ $remarks ?: 'none' }}</span>
</div>

{{-- Section 5: Conclusions --}}
<div class="section-title">5. Conclusions</div>
<table style="width: 100%; border-collapse: collapse; border: none; margin-top: 4px;">
    <tr>
        <td style="width: 23%; vertical-align: top; border: none; padding: 0 4px 0 0;">
            <table style="width: 100%; border: 1.2px solid {{ $resultColor }}; border-radius: 6px; background-color: {{ $result === 'PASSED' ? '#F0FDF4' : ($result === 'FAILED' ? '#FEF2F2' : '#F8FAFC') }}; height: 72px; border-collapse: separate; border-spacing: 0; text-align: center;">
                <tr>
                    <td style="vertical-align: middle; padding: 6px; border: none;">
                        <div style="font-size: 5.6pt; text-transform: uppercase;" class="muted bold"><span style="font-family: Symbol; font-size: 6.5pt; font-weight: bold; margin-right: 2px;">&#8756;</span> Overall Inspection Result</div>
                        <div style="font-size: 11pt; font-weight: bold; color: {{ $resultColor }}; margin-top: 2px;">{{ $result }}</div>
                    </td>
                </tr>
            </table>
        </td>
        @foreach ([
            ['label' => 'Inspected By', 'sig' => $signatures['inspector'], 'role' => 'Inspector', 'name' => $signatures['inspector']['name']],
            ['label' => 'Confirmed By', 'sig' => $signatures['factory'], 'role' => 'Factory Representative', 'name' => $signatures['factory']['name']],
            ['label' => 'Approved By', 'sig' => $signatures['ho'], 'role' => 'MPG HO - MD Production', 'name' => $signatures['ho']['name']],
            ['label' => 'Authorized By', 'sig' => $signatures['director'], 'role' => 'Director', 'name' => $signatures['director']['name']],
        ] as $box)
            <td style="width: 19.25%; vertical-align: top; border: none; padding: 0 0 0 5px;">
                <table style="width: 100%; border: 0.6px solid #CBD5E1; border-radius: 6px; background-color: #F8FAFC; height: 72px; border-collapse: separate; border-spacing: 0; margin: 0; padding: 4px; box-sizing: border-box;">
                    <tr>
                        <td style="vertical-align: top; border: none; padding: 0; text-align: center;">
                            <div style="font-size: 5.6pt; text-transform: uppercase; margin-bottom: 4px;" class="muted bold">{{ $box['label'] }}</div>
                            @if ($box['sig']['state'] === 'signed')
                                <div class="sig-badge" style="display: inline-flex; align-items: center; vertical-align: middle;"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAXklEQVR4nGP8//8/AymAiSTVxGoQ3NUEdwZBDTDFMJpoJ713q2MkqAHZKVidhKwAmQ0znYGBgYERFqzYTENXjGIDugQuMSZCCjDA////MbDAzsb/2MT///+P8AOxAAA4NkZ/eAqFBQAAAABJRU5ErkJggg==" style="width: 7px; height: 7px; margin-right: 2px; vertical-align: middle; margin-top: -1px; display: inline-block;"> Digitally Signed</div>
                                @php
                                    $stampText = !empty($box['sig']['email']) ? $shortEmail($box['sig']['email']) : '';
                                    if (empty($stampText) && $box['label'] !== 'Inspected By') {
                                        $stampText = $box['sig']['name'];
                                    }
                                @endphp
                                @if (!empty($stampText))<div class="muted" style="font-size: 5.2pt; margin-top: 1px;">{{ $stampText }}</div>@endif
                                @if ($box['sig']['date'])<div class="muted" style="font-size: 5.2pt; margin-top: 1px;">{{ $box['sig']['date'] }}</div>@endif
                            @elseif ($box['sig']['state'] === 'rejected')
                                <div class="sig-badge rejected" style="display: inline-flex; align-items: center; vertical-align: middle;"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAY0lEQVR4nJWQ0Q0AIQhDxQluKJnaoWSDd18mnKDxSPigtKRFgPKn6i3RVAmCCe7IpkrNwN2Rp3epfjiJ517W0JktfyyE9stsDoJThiDIPK94+JInZ6JPaFNl9RxsAVc9WgMoL8rWaChiYc43AAAAAElFTkSuQmCC" style="width: 7px; height: 7px; margin-right: 2px; vertical-align: middle; margin-top: -1px; display: inline-block;"> Rejected</div>
                                @php
                                    $stampText = !empty($box['sig']['email']) ? $shortEmail($box['sig']['email']) : '';
                                    if (empty($stampText) && $box['label'] !== 'Inspected By') {
                                        $stampText = $box['sig']['name'];
                                    }
                                @endphp
                                @if (!empty($stampText))<div class="muted" style="font-size: 5.2pt; margin-top: 1px;">{{ $stampText }}</div>@endif
                                @if ($box['sig']['date'])<div class="muted" style="font-size: 5.2pt; margin-top: 1px;">{{ $box['sig']['date'] }}</div>@endif
                            @else
                                <div class="sig-badge pending" style="margin-top: 6px;">{{ $box['label'] === 'Authorized By' ? 'Awaiting Authorization' : 'Awaiting Approval' }}</div>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: bottom; border: none; padding: 0; text-align: center; height: 1px;">
                            <div style="border-top: 0.6px dashed #CBD5E1; padding-top: 2.5px; margin-top: 4px;">
                                @if ($box['name'])
                                    <div style="font-size: 6.2pt; font-weight: bold; line-height: 1.1; margin-bottom: 1px;">{{ $box['name'] }}</div>
                                @endif
                                <div class="muted" style="font-size: 5.2pt; text-transform: uppercase; line-height: 1;">{{ $box['role'] }}</div>
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        @endforeach
    </tr>
</table>

<table style="margin-top: 6px; border-top: 0.6px solid #CBD5E1; padding-top: 4px; width: 100%;">
    <tr>
        <td style="font-size: 5.6pt;" class="muted">Distribution by email: 1. Factory&nbsp; 2. MD Prod&nbsp; 3. PPIC/Finance&nbsp; 4. QA MP</td>
        <td style="font-size: 5.6pt; text-align: right;" class="muted">&raquo; This is an auto-generated document. Final Inspection QC [{{ $generatedAt }} WIB]</td>
    </tr>
</table>

{{-- Page 2: defect photos --}}
@if ($embeddableImages->isNotEmpty())
    <div style="page-break-before: always;"></div>
    <div class="section-title" style="margin-top: 0; margin-bottom: 10px;">6. Defect Photos Attachments</div>
    <table style="width: 100%; border-collapse: collapse; border: none; margin-top: 6px;">
        @foreach ($embeddableImages->chunk(3) as $chunk)
            <tr>
                @foreach ($chunk as $img)
                    <td style="width: 33.33%; vertical-align: top; border: none; padding: 5px;">
                        <table style="width: 100%; border: 0.6px solid #E2E8F0; border-radius: 6px; background-color: #FFFFFF; border-collapse: separate; border-spacing: 0; padding: 6px; text-align: left;">
                            <tr>
                                <td style="border: none; padding: 0;">
                                    <div style="width: 100%; height: 95px; border-radius: 4px; border: 0.6px solid #F1F5F9; background-color: #F8FAFC; text-align: center; line-height: 95px; vertical-align: middle; overflow: hidden;">
                                        <img src="{{ $img->image_path }}" style="max-width: 100%; max-height: 95px; border: none; display: inline-block; vertical-align: middle;">
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td style="border: none; padding: 0; padding-top: 4px;">
                                    <div style="font-size: 5.8pt; font-weight: bold; color: #0F172A; text-transform: uppercase; letter-spacing: 0.02em; margin-top: 2px;">
                                        Defect #{{ $loop->parent->index * 3 + $loop->iteration }} - {{ $img->defect_type ?: 'General' }}
                                    </div>
                                    <div style="font-size: 5.5pt; color: #475569; line-height: 1.3; height: 2.6em; overflow: hidden; margin-top: 2px;" title="{{ trim((string) ($img->description ?? '')) }}">
                                        {{ trim((string) ($img->description ?? '')) ?: 'No description provided.' }}
                                    </div>
                                    <div style="font-size: 5.5pt; font-weight: 600; border-top: 0.6px solid #F1F5F9; padding-top: 4px; margin-top: 4px; color: #0F172A;">
                                        <span style="color: #DC2626;">MAJ: {{ $img->major ?? 0 }}</span> &nbsp;&nbsp;
                                        <span style="color: #D97706;">MIN: {{ $img->minor ?? 0 }}</span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                @endforeach
                @for ($i = count($chunk); $i < 3; $i++)
                    <td style="width: 33.33%; border: none;"></td>
                @endfor
            </tr>
        @endforeach
    </table>
@endif

</body>
</html>
