{{-- Server-side render of the QC Console's inspection report (PrintReport.tsx
     port). Generated by QcReportPdfService for email attachments, verified_doc
     regeneration, and RPA payloads — structural match, DomPDF-compatible
     (tables only, no flexbox). Body extracted into partials/inspection-report-body
     so deduction-report.blade.php can prepend a debit-note page ahead of it. --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    @include('qc.pdf.partials.inspection-report-styles')
</head>
<body>
@include('qc.pdf.partials.inspection-report-body')
</body>
</html>
